# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16fe159d196fcb8af16afebb8ab7803cf35562ff6c0a2c39ff5da2bcbde27b9b5b5e30859bd609510d6672c2ea756697a8633b8153d0c30ed6eb592eaf728082

test:
  secret_key_base: 753799cd539e142d7c8c356722d8b6caca9c01c7698140e17d8ba550d1a30e668a977998bad451a5e310dfd38615d4ae78347a048227dc57f61f12bb2f8be1bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
